const ASAHI_POOL_SNAPSHOT = {
  source: 'BigQuery Data - Client',
  capturedAt: '2026-10-07',
  totalRows: 4914,
  rows: [
    [44,"HxknfRpoKKRn3qsBk","早安美芝城 - 樹林車站概念店","早餐 - 早午餐","新北市","C"],
    [47,"RC2ckzwMYELgezXf4","春申食府","中式 - 合菜","台北市","B"],
    [49,"YTs5SqmqApWGXXMhf","菜其訝","燒烤類 - 炭烤串燒","台北市","A"],
    [50,"rec5mz4qGKmkuWGXZ","食吉健康餐盒","健康餐盒","台北市","C"],
    [51,"Wr6QLTxNC7E3Xzr4Q","丘一司早午餐 - 三重店","早餐 - 早午餐","新北市","C"],
    [52,"mmGJhmowfXf6BARjW","台灣麵","中式 - 麵食","台北市","C"],
    [53,"p2ZrNjahLsgEbMZnD","早安美芝城 - 樹林活力太平店","早餐 - 早午餐","新北市","C"],
    [63,"SfibJSh5HD9daHLPc","老先覺 - 台北莊敬","鍋類 - 台式","台北市","B"],
    [64,"ZczqLs89fA7qcETsa","文湯武醬松山光復店","小吃 - 滷味","台北市","C"],
    [66,"c4jSRZJTWXjmYtFNG","Impromptu by Paul Lee","無菜單及創意料理","台北市","B"],
    [67,"iAvXgqmsZvpkeMcJA","川泰特色料理","亞洲 - 泰式","台北市","B"],
    [71,"tAeqngiBitaZSeAqJ","温咖哩","日式 - 飯食","台北市","B"],
    [73,"ZwWgCHp65eETcwJdH","稻舍食館 - 統一時代","簡餐","台北市","C"],
    [74,"aoe9XwfMiNKxDutrn","稻舍食館 - 微風信義","簡餐","台北市","C"],
    [80,"mdgJ6Tt4ramoT4v2g","三毛食記","亞洲 - 韓式","新北市","B"],
    [91,"NhQhmpfKdZQkc2hhJ","ALLDAYROASTINGCOMPANY","咖啡及輕食","台北市","C"],
    [92,"bWNSgYhnyKGggy85y","炸三小","小吃 - 鹹酥雞","台北市","C"],
    [97,"uN8kub6kDk7PHWopZ","麵線陳專業麵線-林口龜山旗艦店","中式 - 麵食","桃園市","C"],
    [98,"7mRzieTs8Xwe7KwBu","來了就吃","中式 - 麵食","台北市","C"],
    [99,"F3GwBrnRg7mtHCqrM","直火蒸新店店","亞洲 - 韓式","新北市","B"],
    [100,"WdyqtpYDLuJNsSdjk","樂野鍋物","鍋類 - 中價","新北市","B"],
    [101,"XTrY6BEKZBTahDuHk","賞鱻健康鍋物","鍋類 - 其他","台北市","B"],
    [102,"Z6Y4XjWcEFeAk77pZ","westwood - FoH","西式 - 高價","新竹市","B"],
    [103,"bpEvLF55hwnqXS9Ni","Hers bistro 她的餐酒","西式 - 一般","台北市","A"],
    [105,"r72dY6PdDZTzx3btC","咪羅小吃店（酒食條通）","中式 - 熱炒","台北市","A"],
    [106,"QzZs2cYK798k86vDn","潮味決‧湯滷專門店 - 台北大龍分社","小吃 - 滷味","台北市","C"],
    [110,"RrLKmwdvmwpXdwosk","Balloon Coffee 氣球咖啡","咖啡及輕食","新北市","C"],
    [112,"icRNuaSq2JdpvHbwG","珮斯坦咖啡館","咖啡及輕食","台北市","C"],
    [119,"YQJEC5TgKhRxEuSWe","Cantine Marais 瑪黑餐酒","西式 - 高價","台北市","A"],
    [120,"ewEoaxXQgRML9B2E4","焣苑鍋物","鍋類 - 中價","新北市","B"],
    [122,"Jv6sWcB8RMNG2Wgcw","FOCOSO Taipei","西式 - 平價義式","台北市","B"],
    [123,"LWyvajpYABKLp4Ho4","浩克健身早餐 - 延吉店","西式 - 一般","台北市","C"],
    [124,"ZXh6dF7hM4oJDMoE7","丼口飯食","日式 - 飯食","新北市","B"],
    [125,"wwAgDS8DYvtDhBsSh","DiVino Enoteca","西式 - 平價義式","台北市","B"],
    [127,"4s4K3fvsTeQGMJA23","天狗日式串燒","日式 - 居酒屋","台北市","A"],
    [129,"mRnRuDnDFYh3Jq43Q","當心上癮","鍋類 - 中價","台北市","B"],
    [149,"oPHLhv3BKagETepPJ","板橋ABV閣樓餐酒館","","新北市","A"],
    [167,"E38EBHGvHgTkzvNky","昨天餐酒館","","台北市","A"],
    [182,"eqZEYZwETHB5RX9H5","AM弄早餐","","台北市","C"],
    [346,"W5t7nqu8Q9yFaf4SK","Dazzling","咖啡及輕食","台北市","C"],
    [365,"GAJYMD2HXzn4HJGg7","生根有機農場","素食/蔬食 - 西式","新北市","C"],
    [368,"SwuQYsqjtokGrwRmq","哇啦哇啦居酒屋","其他","台北市","A"],
    [370,"pg4vNXGYPuC6nktJh","NAGOMI 中山","複合式Buffet","台北市","B"],
    [371,"fHz2duvw7ALhNbdp9","享食Bar","早餐 - 早午餐","台北市","C"],
    [372,"qf9752yNC6yztEa2K","fifteen 拾吾純植西餐廳","蔬食餐廳 - 複合式","新竹縣","C"],
    [373,"CTcBEavGLBNnqZrD4","漢來-高雄佛陀蔬食廚","素食/蔬食 - 中式","高雄市","C"],
    [376,"e9KNxRZszzq4vjZpQ","欒樹下書房/咖啡","咖啡及輕食","台北市","C"],
    [380,"QcRCry6P8NDPgwXXW","豆府-帕泰家高夢店","亞洲 - 泰式","高雄市","B"],
    [382,"mJpJpsD5ZsRYviySs","又上全食咖啡","蔬食餐廳 - 複合式","台北市","C"],
    [385,"5vKXZwfg3eyaExmyu","九點零一分.Brunch","早餐 - 早午餐","台北市","C"],
    [388,"FyEHkkjNud4KBQMFv","MA CAFE","咖啡及輕食","台北市","C"],
    [389,"g4tGM3MCsxQDYyErZ","IcoNiq Bistro&Bar","西式 - 一般","台北市","A"],
    [390,"ZCjv48YWXZJkreS8Z","老八風_江翠店","日式 - 居酒屋","新北市","A"],
    [391,"fAGj6QXjCs6nEimof","老八風_板橋店","日式 - 居酒屋","新北市","A"],
    [407,"nnB6Bw2nkvj7uQiC9","喫飯食堂-飯菜","中式 - 合菜","台北市","B"],
    [566,"dg6TrvqZtrWL5nNhj","御串房便當","中式 - 自助餐便當","台北市","C"],
    [571,"r4dNXu2tC6ZzbBmtF","作燴 - 莊敬路","中式 - 自助餐便當","台北市","C"],
    [579,"6vsePMvuDf4AMXbLe","菜蟲農食 - 陳怡伶","亞洲 - 韓式","新北市","B"],
    [582,"83eAWb6xk9736HEJm","Cream & Beans(承德店)","咖啡及輕食","台北市","C"],
    [595,"5xp8riD2ngHx9464j","喬伊輕食主義","中式 - 自助餐便當","新北市","C"],
    [623,"HSTRuuXT8WMuLux4E","ten thousand coffee - 六號店 (林口長庚)","咖啡及輕食","桃園市","C"],
    [624,"oBcfWzmAunqkjiPHR","本然蔬食","素食/蔬食 - 中式","新北市","C"],
    [627,"6SByubcxWW9nvjfim","sopung飯捲","亞洲 - 韓式","台北市","B"],
    [628,"X2GEPJdAvPLud9997","小深紅","鍋類 - 台式","新北市","B"],
    [629,"x6nDce9JcPniQj8q4","炭及郎居酒屋","日式 - 居酒屋","新北市","A"],
    [635,"p5awCqCrYbARYR36Q","油花 迴轉吧 燒肉","燒烤類 - 日式燒肉","台北市","B"],
    [648,"E6frhWk5yEHvkS9yL","木盆 - 南京復興門市","素食/蔬食 - 西式","台北市","C"],
    [650,"4saXeNB3xWkjwcXyY","我們這一家","中式 - 麵食","桃園市","C"],
    [659,"CjZXzDtWJZS8vaDpC","火鍋郎","鍋類 - 台式","台北市","B"],
    [663,"uw3trXtfAoWbDBsxZ","All Ears","亞洲 - 泰式","新北市","B"],
    [667,"ihFYnTnHDXmNawhLJ","早安美芝城 - 三重仁美概念店","早餐 - 早午餐","新北市","C"],
    [668,"GQsamDJYsDxgfZabz","炸雞王","小吃 - 鹹酥雞","桃園市","C"],
    [679,"WJ5wRqTqBsBcn4BsE","木盆 - 桃園藝文門市","健康餐盒","桃園市","C"],
    [680,"FrWnWnDExCqG2eZSB","木盆 - 林口長庚門市","健康餐盒","桃園市","C"],
    [688,"Rz22Yf3qdP6Lf6RjE","SOP - 試菜用","西式 - 高價","台北市","B"],
    [690,"Go8F6kJ2RMeEKJYtA","有米真好","中式 - 合菜","新北市","B"],
    [691,"F2RpCuGf294q6cfzj","明水然．樂(信義松菸店)","燒烤類 - 鐵板燒","台北市","B"],
    [696,"6yTC9CXc8zoRhrSdx","張小姐","鍋類 - 中價","台北市","B"],
    [697,"CdYL74DGk8W9RJECu","椰獸精選鍋物","鍋類 - 中價","台北市","B"],
    [698,"XtdQkphit28PzAjCX","囕盈豚(大巨蛋店)","亞洲 - 韓式","台北市","B"],
    [724,"rf2PTR7LAfk8iwc6t","讚碳燒烤","燒烤類 - 炭烤串燒","新北市","A"],
    [767,"T5h3NG5vquqjDp2GE","就是蝴蝶","健康餐盒","台北市","C"],
    [826,"Thpp7Bs6mDbBLdxvF","肉劇場-大直店","鍋類 - 中價","台北市","B"],
    [979,"pvSMM88N8SApTDFNL","呼搭啦串燒","日式 - 居酒屋","台北市","A"],
    [980,"BQcw7dwgf6nwTGmgH","天辣龍江店","鍋類 - 台式","台北市","B"],
    [982,"SdCSCHb6vx5J9jjvj","好吃食堂","中式 - 麵食","台北市","C"],
    [1021,"HspftZ4SCFMPsZij8","喜相逢麵館 - 私房菜","中式 - 麵食","台北市","C"],
    [1044,"B4a9Fp8sBpCp97SHX","林柏食參鍋涮涮鍋","鍋類 - 其他","台北市","B"],
    [1046,"vrudSuCpeLxSrQPKF","旺角鴨味仔","鍋類 - 台式","台北市","B"],
    [1124,"yRdSmhHBncqnMPXju","由你咖啡","咖啡及輕食","台北市","C"],
    [1329,"MrZtD3H6enEjYc9Dk","有饌便當","中式 - 自助餐便當","台北市","C"],
    [1330,"mzAEPa49vtFzJGLJb","長孫shabu-shabu","鍋類 - 中價","台北市","B"],
    [1331,"n9vuMEZ79WpehWezP","好想見麵 - 民生店","中式 - 麵食","台北市","C"],
    [1332,"rSFpQe9fkoLBBhYkG","晴空日居","咖啡及輕食","新北市","C"],
    [1333,"TdXdytxs3FZ9qvwJm","愛米菜-北投店","素食/蔬食 - 中式","台北市","C"],
    [1334,"F7yy7HL9m6yD9yehk","凱哥放生雞","中式 - 自助餐便當","台北市","C"],
    [1340,"FAiNCsN9AyTdH8A6q","oddfish cafe","早餐 - 早午餐","台北市","C"],
    [1341,"Rzrk5kFkGqi9iunu8","天下三絕","中式 - 麵食","台北市","C"],
    [1342,"T2Yx6rRTBJP9h3kMJ","Eat Clean Kitchen","健康餐盒","台北市","C"],
    [1344,"cnEhNvxh4wgqGvqDf","The green room 泰式蔬食","素食/蔬食 - 西式","台北市","C"],
    [1345,"fvnMrgAtS9kuZgpNT","二代福林福州乾拌麵","中式 - 麵食","台北市","C"],
    [1348,"nxap5zYYon7J4KzGB","泰皇御廚便當","亞洲 - 泰式","台北市","B"],
    [1349,"rjyCBzkzhzJ4Jh2LR","Taku日式串燒","日式 - 飯食","台北市","A"],
    [1351,"tp4Hxt2iookRdJXhf","福丸早餐","早餐 - 早午餐","台北市","C"],
    [1354,"9vQefYa8GLt42ZMjv","甩泰咖喱","亞洲 - 泰式","台北市","B"],
    [1356,"WaGwqXJcM7Jw3KCrS","歐浮找餐 - 松江店","早餐 - 早午餐","台北市","C"],
    [1358,"wEX44RL5FBHbhZoBJ","饗小鍋外帶專門店","鍋類 - 台式","新北市","B"],
    [1361,"euyrGjwgAH3B9feku","我其實不想上班","日式 - 飯食","新北市","B"],
    [1362,"nmL7LSeL2Jfm2SLym","雞匠串燒居酒屋","日式 - 居酒屋","台北市","A"],
    [1363,"oy9bZgvqWwvtaFZer","Woosan","燒烤類 - 日式燒肉","台北市","B"],
    [1364,"T2yfDGd453Xy3iLkS","咖哩王","日式 - 飯食","台北市","B"],
    [1370,"uD8sjDrxFF9gKyan9","Baan Taipei (無使用 請搜尋baan）","亞洲 - 泰式","台北市","B"],
    [1371,"8MhEZmKLZRCXEtNJa","刀叉私廚","無菜單及創意料理","台北市","B"],
    [1372,"wcpMyNNx8EFLYzf6X","明日咖啡 - 新富町店","咖啡及輕食","台北市","C"],
    [1375,"WJk7hGi8JF2CR4ZnE","三分半海鮮鍋物","鍋類 - 中價","台北市","B"],
    [1376,"tSyMk3hKswf8uuzm9","涮八秒湯咖哩 - 華興店","日式 - 飯食","新北市","B"],
    [1377,"rKxdGjeNDRvbQAchm","光初日和","早餐 - 早午餐","新北市","C"],
    [1378,"EhYEJZTZfiJjfu9wJ","善自作煮","鍋類 - 中價","台北市","B"],
    [1379,"ZFxqEcNfvLKpFWKC5","醉貓Drunk cat 餐酒館","西式 - 一般","台北市","A"],
    [1380,"gENHsMuN2SknqfQ8y","獅房菜","日式 - 飯食","台北市","B"],
    [1382,"9eYJ7WrFZ2Frnihah","荳上涮涮鍋","鍋類 - 中價","台北市","B"],
    [1460,"G3nPqZvtYBBuCEPkD","君飲咖啡","咖啡及輕食","新北市","C"],
    [1624,"MvZEAwkfext2rCYmJ","To Be Smoothie 台北南京復興店","蔬食餐廳 - 複合式","台北市","C"],
    [1626,"PrDnHWdvw3LTquBvx","威布好食","早餐 - 早午餐","台北市","C"],
    [1627,"9xvTNEdBL7d94Gmk4","喜來登咖啡館","簡餐","台北市","C"],
    [1628,"EPGNxEwMeMDSRmgpY","橋下酒場","日式 - 居酒屋","台北市","A"],
    [1631,"ekMGAPfkg7M8mcz6G","韓太閣","亞洲 - 韓式","台北市","B"],
    [1633,"mLdABuoubiW8876uQ","辛亥池上","中式 - 自助餐便當","台北市","C"],
    [1634,"mweXhqp5NfBnmqWYn","牧食","健康餐盒","台北市","C"],
    [1635,"v9syTm4BngkHjgoWH","鑫吉野烤肉飯信義店","中式 - 自助餐便當","台北市","C"],
    [1636,"N3m5Sj9tcSNqbqmow","巨人鐵板燒","燒烤類 - 鐵板燒","台北市","B"],
    [1637,"4gGbAtZQeQyfn88FP","緣點咖啡","咖啡及輕食","台北市","C"],
    [1638,"CcxLcz6oMFZNn5nv8","哆夶食間","健康餐盒","台北市","C"],
    [1640,"RRqQQYjMArbeTA7Fm","記得我咖啡","西式 - 一般","台北市","C"],
    [1642,"J8GThFtr2qYwjwWn8","玩逗樹桌遊咖啡 - 南京三民店","咖啡及輕食","台北市","C"],
    [1648,"yHRJ76c27aFaGmTdM","天町燒肉芝山店","燒烤類 - 日式燒肉","台北市","B"],
    [1723,"pjC4c68oZCktEmWF8","六六便當店","中式 - 自助餐便當","台北市","C"],
    [1724,"KuaK83KksMxCWPHLM","早安美芝城 信義吳興概念","早餐 - 早午餐","台北市","C"],
    [1725,"a25RxpymBfw9tYmpA","早安美芝城 - 龜山文化概念店","早餐 - 早午餐","桃園市","C"],
    [1726,"5wQqcsWSPvEwrCbv5","早安美芝城 桃園中埔概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1727,"9cvemBkkYxbkdsLGu","早安美芝城 桃園莊一概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1728,"pWcpYMiZtgekYPMXS","早安美芝城 桃園國際概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1729,"AwFGTSowuksmp5iyD","早安美芝城 桃園民生概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1730,"ZAgwpJn3kSkvS3m63","早安美芝城 桃園力行概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1731,"gXaTebKnibZ56Yigc","早安美芝城 桃園大林寺概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1732,"zekQehacMAPmesadW","早安美芝城 桃園經國一概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1733,"LSvS4wix9GRoCpr6R","早安美芝城 蘆竹忠孝概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1734,"Gpu9HpZ4wAMaERakW","早安美芝城 蘆竹大新概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1735,"mR6Jh9b5PwpCoxKiS","早安美芝城 蘆竹中山概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1736,"YGs9fbtXtYm94jZ6u","早安美芝城 中壢元化概念店","早餐 - 傳統早餐店","桃園市","C"],
    [1738,"P2oT6XRvSScj9droh","早安美芝城 - 新店三民概念店","早餐 - 早午餐","新北市","C"],
    [1739,"Dv7MBaHjECSYeN44m","烤食煮義 - 內湖","中式 - 自助餐便當","台北市","C"],
    [1740,"ewBrrF59vXFN8vrug","烤食煮義 - 南港","中式 - 自助餐便當","台北市","C"],
    [1741,"cc2MbF3qSibLBFFjC","早安美芝城 北市安東概念店","早餐 - 早午餐","台北市","C"],
    [1742,"9jyY3dwqYYiGzLTKL","早安美芝城青山概念店","早餐 - 早午餐","桃園市","C"],
    [1743,"PHQa9ZQpNqGhGCqEC","紅花麻辣鹽水雞","小吃 - 夜市","台北市","C"],
    [1746,"HS8MnD4nYGAgoSn3e","向屋日式餐盒","中式 - 自助餐便當","新北市","C"],
    [1753,"TFH7n4P85dZBsFeo8","本苑事業","中式 - 自助餐便當","台北市","C"],
    [1754,"j3mYh6FRzcYnkwcBD","萃茶風健康餐 中和景安店","中式 - 自助餐便當","新北市","C"],
    [1755,"CF88H9w7unQgvQr8m","萃茶風健康餐 東湖店","中式 - 自助餐便當","台北市","C"],
    [1756,"yRfKbN5AFyPCMJajn","PRO健康餐桌 竹北福興店","中式 - 自助餐便當","新竹縣","C"],
    [1758,"Z92L4RYkEEdEyzNhN","作燴 - 光復北路","中式 - 自助餐便當","台北市","C"],
    [1759,"jKe9dTQaLe58yfmof","作燴 - 市民大道","中式 - 自助餐便當","台北市","C"],
    [1761,"v3QJK7Wo3m2vNZevE","作燴 - 忠孝東路","中式 - 自助餐便當","台北市","C"],
    [1762,"wJMsAN5fBjScFPSxe","早安美芝城 - 台北小巨蛋店","早餐 - 傳統早餐店","台北市","C"],
    [1767,"wFyS86qsoJ9P6W76W","MERCER BRUNCH","早餐 - 早午餐","台北市","C"],
    [1768,"HmmRLrrsLnwgpNsen","市府海鮮麵疙瘩","中式 - 麵食","台北市","C"],
    [1771,"F3St5q8PxhK3EYzsT","太朗沖繩飯糰-小巨蛋店","日式 - 飯食","台北市","B"],
    [1772,"Qyx5q5zFHEragmeuT","太朗沖繩飯糰-大安店","日式 - 飯食","台北市","B"],
    [1776,"ZRnux8iyH8zdqmidH","太朗沖繩飯糰-內湖店","日式 - 飯食","台北市","B"],
    [1777,"eGKQrXpvZAEWoXgj9","太朗沖繩飯糰-士林店","日式 - 飯食","台北市","B"],
    [1785,"4wqE8gjpJDodfzC5e","香司相思熱壓吐司","早餐 - 早午餐","新北市","C"],
    [1786,"6rDjZE7BcvtcgfTKe","真芳 - 內湖店","早餐 - 傳統早餐店","台北市","C"],
    [1805,"TRY9YwQupkjW76MNA","太朗沖繩飯糰-農安店","日式 - 飯食","台北市","B"],
    [1813,"tfbJbtM8LmvtzKbkr","鹫炎鹽串燒","燒烤類 - 炭烤串燒","台北市","A"],
    [1816,"gTNMNfQ2on428d9gs","荃國素食 玉成店","中式 - 自助餐便當","台北市","C"],
    [1818,"3p7QcwkMYEtgjBAzr","藏玥心情便當","中式 - 自助餐便當","新北市","C"],
    [1821,"6DEM5yuxbyLLZPt6c","早安美芝城 - 中和圓通概念店","早餐 - 早午餐","新北市","C"],
    [1822,"7RtmBd2CJdBuyCzjL","早安美芝城 - 板橋互助概念店","早餐 - 早午餐","新北市","C"],
    [1829,"aSteh7NFsf6bFqabk","66巷咖啡","中式 - 飯食","台北市","C"],
    [1830,"eA5pZFtPcN4zPLePm","普羅健康餐桌-杭州店","中式 - 自助餐便當","台北市","C"],
    [1831,"eCfzDzRwtfoTigipm","nook - 甜點","咖啡及輕食","台北市","C"],
    [1837,"yHpfXyZzvvgueyvY4","nook - 晚餐","咖啡及輕食","台北市","C"],
    [1841,"m2wmYag8futeSX2Qb","萃茶風健康餐 竹北嘉興店","中式 - 自助餐便當","新竹縣","C"],
    [1844,"kEBHmmQZCX7unyiNR","CHIH POKÉ","健康餐盒","新北市","C"],
    [1846,"2KCDAHZtCycQKhFai","Mabo Poke政大店","健康餐盒","台北市","C"],
    [1847,"2m83iTj7LH9hQbngb","野人舒食 - 板橋店","健康餐盒","新北市","C"],
    [1850,"92jt4DSmjQz4GbNbY","PRESERVE  - 林口三井店(好膳)","素食/蔬食 - 西式","新北市","C"],
    [1854,"H8bHahqMBi46k5erW","飲領食尚","中式 - 自助餐便當","新北市","C"],
    [1858,"JW7PTfpu2njETHW8p","Mabo Poke土城金城加盟店","健康餐盒","新北市","C"],
    [1861,"QXkL6oLA7hQLdgtni","尹東家食品 A01櫃","中式 - 自助餐便當","台北市","C"],
    [1862,"T9SRzGEW4PAbE4fqC","早安美芝城 - 中和景新概念店","早餐 - 早午餐","新北市","C"],
    [1863,"W3XCYWv65xGuYSrTf","早安美芝城-中正西概念店","早餐 - 傳統早餐店","新竹縣","C"],
    [1867,"c96nt5QwEsPW5P7os","黃金波奇","健康餐盒","台北市","C"],
    [1876,"iwA9kKDZDzrNW24AM","早安美芝城 - 中和中和概念店","早餐 - 早午餐","新北市","C"],
    [1877,"kTBj6kSKCfzWsGHa7","尹東家食品 06櫃","中式 - 自助餐便當","台北市","C"],
    [1881,"ud32XSPfDjfD4ScM9","米榭爾布盧 Michel BRU","健康餐盒","新北市","C"],
    [1882,"ueBWXuimbEMug8D3Q","早安美芝城 - 永和竹林概念店","早餐 - 早午餐","新北市","C"],
    [1883,"yAvymQwnvndEhTYfm","早安美芝城 - 中和活力興南","早餐 - 早午餐","新北市","C"],
    [1884,"z5Ak5pf3BqDz52Svt","丘一司早午餐 - 社子店","早餐 - 早午餐","台北市","C"],
    [1886,"Anw7twoz8Zn8YMf3h","熊霸鍋燒專賣店","鍋類 - 台式","新北市","B"],
    [1887,"Koavrp68MzdN5Du3S","上野烤肉飯-南港店","中式 - 自助餐便當","台北市","C"],
    [1889,"7BJoydyNvbR2rYPi2","菜菜優纖 土城店","中式 - 自助餐便當","新北市","C"],
    [1891,"CLqLQjWapn4L3wZfX","早安美芝城 - 板橋四川概念店","早餐 - 早午餐","新北市","C"],
    [1893,"SMN7L9JM3itm5aC6A","M One Cafe - 新光 A11","早餐 - 早午餐","台北市","C"],
    [1894,"bvpu8rJKYAk2DAZNS","真芳 - 圓山店","早餐 - 早午餐","台北市","C"],
    [1895,"tNybTWcbzMbHnFcdw","M One Cafe - 大安館","早餐 - 早午餐","台北市","C"],
    [1897,"JTWDunWQe9Ki38MP3","早安美芝城 - 文山木新概念店","早餐 - 早午餐","台北市","C"],
    [1898,"R9KPadwyJqhWiEkgD","早安美芝城 - 新店光明概念店","早餐 - 早午餐","新北市","C"],
    [1905,"rYHjxFHpgr2dFFBh2","菓匠 香珀坊","咖啡及輕食","新北市","C"],
    [1906,"McEkSp8E7rfQedKKp","PAUL 新竹巨城店","西式 - 法式","新竹市","B"],
    [1908,"8BfmSna4p63hhLNpm","早安美芝城 - 新竹科園概念店","早餐 - 傳統早餐店","新竹市","C"],
    [1915,"MLFGH24M84Y7bTt8u","早安美芝城 - 信義松德概念店","早餐 - 早午餐","台北市","C"],
    [1927,"pjDhWrSPPpXExhF7y","米克吐司","早餐 - 早午餐","台北市","C"],
    [1942,"2pYu3jiEKqMLuDcfs","萃茶風健康餐 鶯歌鳳鳴店","中式 - 自助餐便當","新北市","C"],
    [1943,"3tD8D3ByncHdzgBgC","丸林民族","中式 - 自助餐便當","台北市","C"],
    [1944,"RAer8cswmpibTPg8E","樑記文華雞","中式 - 自助餐便當","台北市","C"],
    [1954,"Cqgw4Ze2SaeeS7CaC","左爺爺咖啡廳","咖啡及輕食","台北市","C"],
    [1955,"FqSPfBRz6DdEnnPos","菜蟲農食 - 褚立陽","西式 - 平價義式","台北市","B"],
    [1957,"vRRsD7eHC24E2Y5qe","趙芷屏","中式 - 合菜","桃園市","B"],
    [1962,"2vRw7GbZYSAZxDTjp","東大門韓式料理","亞洲 - 韓式","台北市","B"],
    [1964,"4EeSnpgzk8ie8qMix","澳門贏到足 鍋物私房菜 （信義本店）","鍋類 - 中價","台北市","B"],
    [1973,"CdF3cz7YMiEagtETs","小仺館-自取","咖啡及輕食","新北市","C"],
    [1975,"CtxZbtsvLA436eyk2","早安美芝城 - 北市孔廟概念店","早餐 - 早午餐","台北市","C"],
    [1989,"XLXnBgPJrMKjn4PN7","生地餅舖","西式 - 平價義式","新竹市","B"],
    [1994,"eeChCpcbRErJze6GT","丸麵鋪","中式 - 麵食","台北市","C"],
    [1997,"iSrZxiSijELwv7zJB","點心源 港式點心簡餐廳","中式 - 其他","新北市","C"],
    [2002,"p3TGCfJo6kNwQs9cn","Clover","西式 - 法式","台北市","B"],
    [2016,"AXTF3DzZXwBuSucZG","檳城炒粿條（西湖）","中式 - 熱炒","台北市","B"],
    [2018,"DqqmME88bN6ycpKvX","榮食堂","日式 - 飯食","台北市","B"],
    [2019,"KrQcAdvLhStXNEeki","嗨Hi","早餐 - 早午餐","台北市","C"],
    [2025,"t3fvdRKMEcwbRBGXW","真芳 - 台北車站","早餐 - 早午餐","台北市","C"],
    [2031,"3nK7X25rLZnYBGAvF","BEAN U","素食/蔬食 - 西式","台北市","C"],
    [2032,"4W8daxvS7AbWbuYkB","夏綠蒂·小私廚","西式 - 平價義式","台北市","B"],
    [2034,"5c3AH3GgPGjSFp7uY","鳥作珈琲","咖啡及輕食","台北市","C"],
    [2035,"8PRaK3FS5SQrD8i5t","Mabo Poke新莊復興店","健康餐盒","新北市","C"],
    [2039,"Gtag6GAyPt6M698R9","Mabo Poke板橋致理店","健康餐盒","新北市","C"],
    [2040,"GumQmfodctALfdeQ5","味自慢牛排","燒烤類 - 牛排","台北市","B"],
    [2041,"HAK3zG9wq7DqH3mir","TCT","早餐 - 早午餐","台北市","C"],
    [2043,"PZdfesByMgfEAouYt","蜉蝣喫茶Poké me","健康餐盒","新北市","C"],
    [2044,"Pui9eoW99vZZEKxkN","鳥作洋食","日式 - 飯食","台北市","B"],
    [2046,"RWsusyKSBnMwBmrMM","Shavu 刷刷 日式涮涮鍋","鍋類 - 中價","台北市","B"],
    [2050,"WddrzQRWBRCkiu7SW","燈籠滷味","小吃 - 滷味","台北市","C"],
    [2054,"bBkmgWkE8hLJHahsf","吉飽 - 天母德行店","早餐 - 早午餐","台北市","C"],
    [2055,"cTTgkmPKbMbMeGXoa","早安美芝城 - 林口勵馨概念店","早餐 - 早午餐","新北市","C"],
    [2062,"mYrHW7SM3uiJa53Ze","J。WOW 酒窩義式餐酒館","西式 - 高價","新北市","A"],
    [2068,"H3xb4qp4cjrt5hDAj","Mabo Poke林口民富店","健康餐盒","新北市","C"],
    [2069,"KfsHtW8oXujFBSbEx","PAUL大直忠泰店","西式 - 法式","台北市","B"],
    [2070,"DRstPs3wcgW2TrTtw","PAUL仁愛店","西式 - 法式","台北市","B"],
    [2072,"5CyQjHEFTA5aCHXZP","CWTCH YUE 擁躍","西式 - 法式","台北市","B"],
    [2073,"syueKr2FnptJpPP6x","早安美芝城 中和景平概念店","早餐 - 早午餐","新北市","C"],
    [2074,"bPoc7cydHpYGYJMpf","小露台","西式 - 高價","新北市","B"],
    [2079,"3rsrbvoTQiw7oCbQB","桃猿快樂熱炒區（樂天青埔棒球場）","中式 - 熱炒","桃園市","B"],
    [2089,"bZNFgTrNcPEGgEAMK","Mabo Poke永和樂華店","健康餐盒","新北市","C"],
    [2091,"gcKpp4XbTBXns76NM","股感媒體龍焰燒烤席","燒烤類 - 鐵板燒","台北市","B"],
    [2095,"L5pSsYEmCAckfDWKr","棠棠dondonstudio","咖啡及輕食","台北市","C"],
    [2096,"9BieT4uJ6mJryxEvZ","食尚曼谷大巨蛋店","亞洲 - 泰式","台北市","B"],
    [2121,"pZMHGtodM9nXEX6sN","真芳萬芳-興隆店","早餐 - 早午餐","台北市","C"],
    [2140,"nnZ4MEEWxhCDxrkBS","TheTen Curry","日式 - 飯食","台北市","B"],
    [2144,"26uFEXdTDhPHaM6no","上善蔬食 - 忠孝店","素食/蔬食 - 中式","台北市","C"],
    [2151,"8v56nPGtmLyu2JL6x","莎娃低卡健康餐盒","亞洲 - 泰式","高雄市","B"],
    [2152,"rQCyCT72aRv9osf7Z","The Common Table","咖啡及輕食","台北市","C"],
    [2161,"5M9haaB8R4CCFLtBh","68食堂","中式 - 合菜","台北市","B"],
    [2166,"CHCfAthJ4TeJv2Wye","丰錞咖啡所","咖啡及輕食","新北市","C"],
    [2188,"gnaBv84hvW33xTXnH","鼎楓寶島火鍋","鍋類 - 中價","台北市","B"],
    [2198,"vHwtg8L6cSJiuLZhg","一粒万福","日式 - 飯食","台北市","B"],
    [2200,"najaMykfdyBQtwBvW","Poke 爺爺","健康餐盒","新北市","C"],
    [2201,"6e2aEe8RvFgDYYBrS","GOOD DAY CAFE by mrs inkolize","咖啡及輕食","台北市","C"],
    [2202,"R9xyMcknQApZC7TQA","土山本家","日式 - 日式麵食專賣","台北市","C"],
    [2204,"4AoqbxsZbk2n9XEh4","拉亞伊通店","早餐 - 傳統早餐店","台北市","C"],
    [2206,"CK2HGBmCZEb7co9NE","Brasa西班牙餐酒館","西式 - 一般","新北市","A"],
    [2207,"CZL7Ljyxpqx5Zqc2t","厚舖涮涮鍋 Encore新莊","鍋類 - 台式","新北市","B"],
    [2209,"DQMNX8DZZk8dicZmS","醇享虹吸咖啡","咖啡及輕食","新北市","C"],
    [2213,"SQ7ony4rXDgyrPwgg","名古屋備長鈴成","日式 - 飯食","台北市","B"],
    [2221,"eeFCRxueWHnz5JRja","緩緩商行.","簡餐","新北市","C"],
    [2222,"MsknDbwXDsGfN4a4m","翁士竣 個人單","西式 - 平價義式","新北市","B"],
    [2223,"TP6CStNNDSypXfJLA","植饗受playinjoy","素食/蔬食 - 西式","台北市","C"],
    [2226,"jKoaDHSsvQcZZXyZo","起司日和by慢慢弄","咖啡及輕食","台北市","C"],
    [2227,"o9hbxPZ6vMkmXQ3MY","Mabo Poke松山南京店","健康餐盒","台北市","C"],
    [2229,"WLcsZRjGb9g5xWLoS","起司日和 - 總部單","咖啡及輕食","台北市","C"],
    [2230,"jk5jEH8oQvrGSRACi","午狄 輕食 ｜咖啡","","台北市","C"],
    [2234,"FynJBs6Sw7vsF9HQY","昔日大飯店","西式 - 平價義式","新北市","B"],
    [2245,"NadbZJK8CFqfLdxp2","The Mini Club","咖啡及輕食","台北市","C"],
    [2247,"WYzFDMjKYzqsEpD86","厚舖涮涮鍋-中平路新店","鍋類 - 台式","新北市","B"],
    [2248,"doK9Gq3jQAXYoASEu","La Salita Bistro 小房間餐酒館","西式 - 高價","台北市","A"],
    [2255,"yJnszMqTkaxTDcQGu","金晶雞","中式 - 合菜","台北市","B"],
    [2257,"shfqKZFyYjuz9LPFJ","暫停工作室","咖啡及輕食","台北市","C"],
    [2265,"2upXE3fJnTLZDnnWq","布拉格咖啡館","咖啡及輕食","台北市","C"],
    [2266,"5oZXyYTrxaXX78Kr6","燒石鼎石頭小火鍋 新店建國店","鍋類 - 台式","新北市","B"],
    [2280,"ukPfFwesK9cTXXcPn","PAUSE Coffee Roaster","咖啡及輕食","台北市","C"],
    [2288,"DSKfjP2aGGjFAxtKW","波奇兔兔poke & two","健康餐盒","台北市","C"],
    [2290,"S445fKAtMcT2cv2WD","食堂平浪","日式 - 居酒屋","台北市","A"],
    [2291,"aqzcms3ukqv9neHDG","奶油蛋糕咖啡廳","甜點及甜品","新北市","C"],
    [2302,"JL2uNksJTH9kKiJfv","楓聖居酒屋","燒烤類 - 炭烤串燒","彰化縣","A"],
    [2303,"pGxaWfpS8N6SuLD79","牛肆食堂","燒烤類 - 日式燒肉","台北市","B"],
    [2306,"iaotKjMnH8Zhc6zpp","一鮮鍋","鍋類 - 台式","新北市","B"],
    [2311,"zTZKFvsncNRztFQW9","油飯水餃","中式 - 麵食","新北市","C"],
    [2312,"ipF9guX66mFb6LS7d","Mume","西式 - 高價","台北市","B"],
    [2315,"jB57KDkLjEuyk2HAt","紅花麻辣鹽水雞 永和樂華店","小吃 - 滷味","新北市","C"],
    [2319,"wgEFmYeGnF6FbPacj","維記火鍋","鍋類 - 高價","台北市","B"],
    [2326,"PQ67R22u43HLcgoim","La MESA - 中山店","西式 - 高價","台北市","B"],
    [2328,"GGJfbE24dRmuattp9","南京七里香麻辣鴨血臭豆腐","小吃 - 滷味","台北市","C"],
    [2335,"PZ3cKqMx5N73MvNEh","山野-YAMANO-無菜單日本料理","日式 - 生魚片、壽司專賣","台北市","B"],
    [2338,"qZrNxozjXSc6bQmYA","四知堂 - 政大公企","中式 - 合菜","台北市","B"],
    [2361,"o4X49EChwLZfEaHn3","燒肉擔當","燒烤類 - 日式燒肉","台北市","B"],
    [2367,"N6rSFukgebJLz9H62","金月日式鍋物擔當","鍋類 - 高價","台北市","B"],
    [2369,"kGNCGHxH2aGqq4Y2k","FUTORU","日式 - 居酒屋","台北市","A"],
    [2370,"4W2NyycQnpRx64rCG","料韓男｜韓國熟成烤五花肉 - 明曜店","亞洲 - 韓式","台北市","B"],
    [2372,"MhqvBNK6p5794eECK","吉祥素食堂","中式 - 自助餐便當","新北市","C"],
    [2385,"kEGKsbQmgGAyCJptQ","慢慢釀鹹水雞","小吃 - 滷味","高雄市","C"],
    [2390,"kcxZtYLRvfGaBo9fs","梅亭蜜汁燒烤 內壢店","燒烤類 - 炭烤串燒","桃園市","A"],
    [2393,"4oJhYtvaXCKtEeere","Bar THY _員餐","中式 - 合菜","台北市","B"],
    [2394,"9YcaMiApwMWrecFKC","Bar THY","中式 - 合菜","台北市","B"],
    [2410,"wFYbmzM2ttoYMkmBj","迦拿餐酒館","西式 - 一般","台北市","A"],
    [2413,"KHhdKrHJpEwKRSmPW","Bar Kawa 川","西式 - 平價義式","台北市","B"],
    [2420,"ZEfcWXdWLiEuMXAqu","喵屋","簡餐","台北市","C"],
    [2421,"mnaTomMWEssNwHWAH","餓侍餾bar","日式 - 居酒屋","台北市","A"],
    [2424,"ZMH8FmCWFgzp6cSmy","紀香無骨炸雞 安一店","小吃 - 鹹酥雞","基隆市","C"],
    [2430,"HwEhzfewkdHbh9GfE","食二日式燒烤 南崁店","燒烤類 - 日式燒肉","桃園市","B"],
    [2448,"PpKdNgzX3bNzcgSx9","盒你胃手作餐盒","中式 - 自助餐便當","台北市","C"],
    [2458,"4AKBPKrGszZwBJNrd","麵屋輝","日式 - 日式麵食專賣","台北市","C"],
    [2466,"d5MobMQBLdodvkq5z","D.G. CAFE","簡餐","台北市","C"],
    [2471,"ibfTpHANdfjBZi9du","小植茁植物料理","中式 - 麵食","台北市","C"],
    [2482,"sD4KKJ7NSckpYxzBF","生活在他方 - 本店","咖啡及輕食","新北市","C"],
    [2486,"Tz96fTYdJh9Qj6arZ","糧心傑作早午餐","早餐 - 早午餐","新北市","C"],
    [2491,"8Y68aagEeydz8aQEG","一碗來","中式 - 麵食","台北市","C"],
    [2493,"3zKbt79HiX6ogCpvH","厚舖涮涮鍋plus天母店","鍋類 - 中價","台北市","B"],
    [2494,"6puhrqgifXfMubbsi","神保町燒肉 - 信義","燒烤類 - 日式燒肉","台北市","B"],
    [2496,"hBBD8GWuuEXBPmkyb","True Box","健康餐盒","新北市","C"],
    [2500,"gr3EB8MJ9Zwvn9ZC9","盒心肌群","健康餐盒","台北市","C"],
    [2511,"EdwPLFo7J98AD6fh8","佐藤精肉店 - 八德店","日式 - 飯食","台北市","B"],
    [2532,"gp46i6bGJ6twRvhYx","好物 Spirit 咖啡","咖啡及輕食","台北市","C"],
    [2544,"zNLnbbefFS7fhpGii","Cafe Koreatime","咖啡及輕食","台北市","C"],
    [2550,"eewZrdFWYi6c5nZuK","真飽餐盒","健康餐盒","台北市","C"],
    [2551,"ho6Sam4pn8PGxWuTL","AW Cafe Wine Bistro","咖啡及輕食","台北市","C"],
    [2552,"sdaaryWiGDJFYrsJQ","文火處方","簡餐","台北市","C"],
    [2553,"E8baDCevh8DSZuP6f","沐樂咖啡-新生店","咖啡及輕食","台北市","C"],
    [2558,"L9zcbjbpPTs5otoYN","杉尚煮鍋","鍋類 - 高價","台北市","B"],
    [2563,"rk5yFm4Gqj8RZH5RX","盛櫥","早餐 - 早午餐","台北市","C"],
    [2567,"466kDB279cqioKzk8","苗林行","西式 - 法式","台北市","B"],
    [2588,"XifXboP5qNsW3gcAB","小器食堂 - 中山店","日式 - 飯食","台北市","B"],
    [2602,"rqXsc9Y48ZE5AWvEK","勝利小吃店","西式 - 一般","台北市","C"],
    [2603,"Cgc7idQDhYQZDeKaj","魚目咖啡","日式 - 飯食","台北市","B"],
    [2605,"MNYyhod2pfQ7kCQAc","Jana cafe嚼咖啡餐廳","咖啡及輕食","台北市","C"],
    [2623,"3zhoR3gPKHAQ5vaYg","石撈","鍋類 - 中價","台北市","B"],
    [2630,"CJai9HTatKEsqnp6f","Kame house Hawaii 逸仙店","燒烤類 - 鐵板燒","台北市","B"],
    [2635,"N2enYEnW39WPkvMo8","和韵WAING","西式 - 法式","台北市","B"],
    [2637,"XPkQiGXyS2BXP9ApK","旭舊cafe","咖啡及輕食","新北市","C"],
    [2640,"mSC8Qc4paTaQPSye7","佛斯特旺餐酒館","西式 - 一般","台北市","A"],
    [2649,"m2B74LyFjt4N6A5FQ","Birdy yakitori - 內場","燒烤類 - 炭烤串燒","台北市","A"],
    [2650,"rAPXvdcJs9GSYXF2M","Birdy yakitori","燒烤類 - 炭烤串燒","台北市","A"],
    [2652,"RnuHia9oq263v7ZTx","雅痞咖啡","亞洲 - 其他","台北市","C"],
    [2663,"zWFazjeL6h3ndar7Y","Kame kona Hawaii 安和店","燒烤類 - 鐵板燒","台北市","B"],
    [2665,"6edwx4TfGugR9PeAm","營火CampfireCafe","咖啡及輕食","台北市","C"],
    [2672,"vYma7avpMyiEdHyET","元心燃","鍋類 - 中價","台北市","B"],
    [2682,"x8gTy8XNTSjmxhSvr","Catmint Café&bar 貓草餐酒館","其他","新北市","A"],
    [2724,"WQbjy33AZPSbBCiwZ","丘一司早午餐 - 遼寧店","早餐 - 早午餐","台北市","C"],
    [2731,"wEjTeGqJyDQkmdCn5","菜菜優纖","素食/蔬食 - 中式","台北市","C"],
    [2746,"DPxiKEuoN7zjxJ23J","丘一司早午餐 - 大安店","早餐 - 早午餐","台北市","C"],
    [2848,"jWJoi4MfgYaZFXMFW","潮饌麵府","中式 - 麵食","台北市","C"],
    [3128,"beAZo5zuRi3omiw2i","AW","咖啡及輕食","台北市","C"],
    [3804,"D2HWwog6RTGz9tePw","休習日","咖啡及輕食","台北市","C"],
    [3821,"LedJaKfoyQ8wz3GeE","貓食光","咖啡及輕食","台北市","C"],
    [3824,"2BBDsp5oCsPdKfbv2","COQUOLOGY料理生活","早餐 - 早午餐","台北市","C"],
    [3825,"97foKLevCaJTvrKc3","特有種商行","簡餐","台北市","C"],
    [3835,"DrtPBvSdAZ5SHNjrG","等一個人咖啡-景美店","早餐 - 早午餐","台北市","C"],
    [3847,"thGm2ZbMb5vGpcr7E","拼拼拌-敦南站","亞洲 - 韓式","台北市","B"],
    [3852,"Wfp2sy74WHKyHACTk","兔Dreams","咖啡及輕食","台北市","C"],
    [3859,"pZin5RtsHaXY9KXMF","2J cafe","咖啡及輕食","台北市","C"],
    [3866,"a933vBm4DxTMxMbAN","信宅食堂餐酒館","西式 - 一般","台北市","A"],
    [3873,"37iktL9YHtGtgqbTy","N+n喫早餐","早餐 - 早午餐","台北市","C"],
    [3875,"Yy6uGyrAQAb8gvByq","真芳-民生店","早餐 - 傳統早餐店","台北市","C"],
    [3887,"oN7mg2oW9E83g32hC","真芳-信義店","早餐 - 傳統早餐店","台北市","C"],
    [3889,"NNNuLPWN5YhFfaxzT","以馬忤斯","西式 - 法式","台北市","B"],
    [3890,"TkhQS5t7AFLvSEWrT","你好咖啡旅館","咖啡及輕食","台北市","C"],
    [3893,"fFkfKEh8ftpDsJ5Sr","真芳-大安店","早餐 - 傳統早餐店","台北市","C"],
    [3895,"742fesbNidGWbXzwv","真芳-民生社區店","咖啡及輕食","台北市","C"],
    [3899,"5xC4n5mer6a94cj4B","真芳-長安店","早餐 - 傳統早餐店","台北市","C"],
    [3900,"8uqNbXAauSA87dP2u","Humble beginnings café","咖啡及輕食","台北市","C"],
    [3903,"9zXu8dE8jPGz98LZZ","Little by Little","早餐 - 早午餐","台北市","C"],
    [3938,"3mJ3BmAqv5q6XM9tN","132糧倉","西式 - 高價","新竹市","B"],
    [3973,"vjasS6YjPQ4SZFWRe","小器食堂 - 微風南山atre店","日式 - 飯食","台北市","B"],
    [3974,"zReQbbFh5eRPBXKic","小器食堂 - 華山店","日式 - 飯食","台北市","B"],
    [3994,"68MdwgCoB6s9PcZdi","The Hippo Coffee Bar","早餐 - 早午餐","台北市","C"],
    [4043,"WehhN6gwzsPgwPXsM","Saturn Landing Turkish Coffee 登陸土星土耳其咖啡","咖啡及輕食","台北市","C"],
    [4140,"kGs4t3GTydWfG76bs","越鄉 素食","亞洲 - 越式","台北市","C"],
    [4141,"svhv9YRwaFbWmA8TK","泰和樓股份有限公司","中式 - 合菜","台北市","B"],
    [4155,"R2wM4pt9M8sYLx7sf","雞男","健康餐盒","台北市","C"],
    [4157,"ykoXurntsQawcYNPB","佳裕香冒菜涼皮","中式 - 麵食","台北市","C"],
    [4159,"L9Ft358TP4zRo5ihc","福甘心","健康餐盒","新北市","C"],
    [4160,"a6pnhchfyJfchNnug","Le SAGE 餐酒館","西式 - 一般","台北市","A"],
    [4165,"tWoAKGLJbfb7MbADj","元香廚坊","中式 - 麵食","台北市","C"],
    [4167,"BbMXTjNxEQdcddQ74","奧圖美咖啡餐酒館-信義店","西式 - 一般","台北市","A"],
    [4168,"K4jdrWhM84tv8ekZJ","阿不拉手作甜不辣","小吃 - 滷味","台北市","C"],
    [4170,"7bTBCKiernq4i4ZN4","上海鄉村 - 新生店","中式 - 合菜","新北市","B"],
    [4171,"Pxid2AgvfbCwqjxid","上海鄉村 - 仁愛店","中式 - 合菜","新北市","B"],
    [4173,"3KqoyLgYYvgcDTgca","晶宴  - 總經理室","中式 - 合菜","新北市","B"],
    [4175,"h7ufCBMbRJ3PWE6Fg","晶宴  - 採購部","中式 - 合菜","新北市","B"],
    [4177,"B5GoY6svxXRnXcWTs","鼎記製餃 - 截切廠 - 侑鮮芬芳","中式 - 麵食","新北市","C"],
    [4178,"Nsgb7p2TQLr5yMATP","鼎記製餃 - 本廠","中式 - 麵食","新北市","C"],
    [4180,"eMRbD8FswnTMzhKq5","欣葉台菜-信義A9店 - 追加","中式 - 合菜","台北市","B"],
    [4183,"yv4WtjMRkZYvCMJ7p","欣葉台菜-信義A9店","中式 - 合菜","台北市","B"],
    [4193,"Awfazbcc9L5eLHQLR","台北香格里拉 - 6F咖啡 - CAFE AT FAR EASTERN KITCHEN-2","其他","台北市","C"],
    [4210,"TsATmPqEFs3txsghT","台北香格里拉 - 6F咖啡 - CAFE AT FAR EASTERN SERVICE-1","其他","台北市","C"],
    [4212,"Y4DiPbXh8o67etwpu","台北香格里拉 - 6F咖啡 - CAFE AT FAR EASTERN KITCHEN-3","其他","台北市","C"],
    [4219,"eYgZSmMMSH5fpYpYE","Mia Dreamers coffee 林口扶輪公園店(加盟)","咖啡及輕食","新北市","C"],
    [4222,"fNnQgq3vpXBQYw6FF","台北香格里拉 - LI BAI LOUNGE KITCHEN- 1","中式 - 合菜","台北市","B"],
    [4225,"hEyGcE67wzbfWXdfR","台北香格里拉 - 6F咖啡 - CAFE AT FAR EASTERN KITCHEN-4","其他","台北市","C"],
    [4226,"jx5vMwu3h9wQS8kDo","台北香格里拉 - 6F咖啡 - CAFE AT FAR EASTERN KITCHEN-1","其他","台北市","C"],
    [4257,"xGuDqMjhwQsWW8ACm","格萊天漾 - 咖啡生鮮倉 -2","中式 - 其他","台北市","C"],
    [4269,"tY7mKw3aWbc2kcEf5","Mia MOO","素食/蔬食 - 西式","台北市","C"],
    [4271,"ZB5dzQ7HmmXvppecb","燒肉LIKE-中和環球店","燒烤類 - 日式燒肉","新北市","B"],
    [4272,"mvBJ7tnwigbeNGBan","燒肉LIKE-信義威秀店","燒烤類 - 日式燒肉","台北市","B"],
    [4273,"qf9kb7HZ2uqe6dAcF","燒肉LIKE-三重CITY LINK店","燒烤類 - 日式燒肉","新北市","B"],
    [4274,"tiw45BZPqb7buDRDP","燒肉LIKE-天母SOGO店","燒烤類 - 日式燒肉","台北市","B"],
    [4275,"zQQM5wD7zwAQuxXGQ","燒肉LIKE-新店家樂福店","燒烤類 - 日式燒肉","新北市","B"],
    [4283,"XPdxiv4HGYHbZQJ2s","燒肉LIKE_新竹巨城店","燒烤類 - 日式燒肉","新竹市","B"],
    [4288,"m7YjfWesatb9jZThg","漢來-巨蛋海港廚","素食/蔬食 - 中式","高雄市","C"],
    [4300,"aB5gRgddJhAiMKDLQ","煙波飯店(湖濱館) - 溫莎宴廚 -  3","複合式Buffet","新竹市","B"],
    [4332,"qYyfh7YNkFfvs7WJL","台北凱撒大飯店-咖啡園-2","其他","台北市","C"],
    [4339,"N7LXi2rspipfypeTK","燒肉LIKE_總公司","燒烤類 - 日式燒肉","台北市","B"],
    [4383,"XcssHiXe2n5YSvzF9","燒肉LIKE_台中勤美店","燒烤類 - 日式燒肉","台中市","B"],
    [4388,"dF4E98dLFmirw2nNi","Hervivore - 復興店(國椿)-追加","素食/蔬食 - 西式","台北市","C"],
    [4392,"fLBy4euMcxgFApsRC","燒肉LIKE_台北京站","燒烤類 - 日式燒肉","台北市","B"],
    [4397,"hym8jkEpK4596usWe","燒肉LIKE-新莊宏匯店","燒烤類 - 日式燒肉","新北市","B"],
    [4400,"kQLGMCkYmCWrqRkw5","燒肉LIKE_桃園新光影城","燒烤類 - 日式燒肉","桃園市","B"],
    [4405,"qskrCg7GSxhhsro8q","燒肉LIKE_桃園中壢站前店","燒烤類 - 日式燒肉","桃園市","B"],
    [4433,"JW76Q7JSk3GAgifLz","萬華凱達大飯店-早餐倉-3","其他","台北市","C"],
    [4481,"xhxuZSaqHofcWdmFT","Happy Farmer  - 桃園站前店(Mia)","素食/蔬食 - 西式","桃園市","C"],
    [4488,"9eEXDMTYDAN5iA7Ye","晶宴  - 府中館廚務課","中式 - 合菜","新北市","B"],
    [4489,"9qHyNpGNdjnoZ3DTT","晶宴  - 中和館廚務課","中式 - 合菜","新北市","B"],
    [4491,"MJAg4xxEPFBTuFvQT","晶宴  - 中和館西點廚務課","中式 - 合菜","新北市","B"],
    [4494,"Pp9ePtBeQYqEA99ca","晶宴  - 民生館廚務課","中式 - 合菜","台北市","B"],
    [4495,"QBazPRQErXPbt3gFM","晶宴  - 中和館燒臘課","中式 - 合菜","新北市","B"],
    [4498,"YLXhBcvw5if7wdRiX","晶宴  - 中和館客服課","中式 - 合菜","新北市","B"],
    [4499,"YjDzWnmLCTQawmzce","晶宴  - 新莊館廚務課","中式 - 合菜","新北市","B"],
    [4500,"adCky9Cj9xm6BBLz9","晶宴  - 民權館廚務課","中式 - 合菜","台北市","B"],
    [4501,"b2CNoHvGP6gPhCEkv","晶宴  - 民權館客服課","中式 - 合菜","台北市","B"],
    [4504,"jaLSELDifP25D4Feq","晶宴  - 府中館客服課","中式 - 合菜","新北市","B"],
    [4505,"kRKexwHtLcd8CDy3S","晶宴  - 新莊館客服課","中式 - 合菜","新北市","B"],
    [4507,"mKtZW7uxCs4gg9GTb","晶宴  - 鴨覓","中式 - 合菜","台北市","B"],
    [4508,"pD3Eo6jfQswv9aZhv","晶宴  - 民生館客服課","中式 - 合菜","台北市","B"],
    [4509,"28X8mSXTNRoa2Fe6J","Mia Cucina-Dreamers Coffee忠誠公園","素食/蔬食 - 西式","台北市","C"],
    [4514,"E3GWaA7Pc8P4szEze","PRESERVE - 南港LALAPORT店(好膳)","素食/蔬食 - 西式","台北市","C"],
    [4518,"QdxKEDEMwnirCy4E2","Mia Cucina-Dreamers Coffee永康","素食/蔬食 - 西式","台北市","C"],
    [4519,"TtfE7Z2xEQLr9fBJw","PRESERVE - 大巨蛋店(好膳)","素食/蔬食 - 西式","台北市","C"],
    [4520,"XB5pdDkcG3G5Etnsy","Mia Cucina-Dreamers Coffee忠誠","素食/蔬食 - 西式","台北市","C"],
    [4523,"kdQvJ4BopKcfJi2ok","Mia Cucina -Dreamers Coffee信義A8","素食/蔬食 - 西式","台北市","C"],
    [4524,"nE8FAsbHXaYtk7s7v","Mia Cucina-Dreamers Coffee新店寶橋","素食/蔬食 - 西式","新北市","C"],
    [4525,"rpJmxjdyRNokktrr5","雅樂軒 Aloft - 早餐外場","早餐 - 早午餐","台北市","C"],
    [4527,"9t8RP9wWT6sh8SjES","木盆 - 松江長安門市","素食/蔬食 - 西式","台北市","C"],
    [4528,"Aq7QFTt2u2iBZbeAQ","台北國賓 - A CUT牛排館 2","西式 - 高價","台北市","B"],
    [4529,"J35KY38mbZ5pGvcvz","木盆 - 內湖港墘門市","素食/蔬食 - 西式","台北市","C"],
    [4534,"swEF7SgGK9WXw993Y","木盆 - 永春門市","素食/蔬食 - 西式","台北市","C"],
    [4545,"EwBeEJ3s5R5hG2hiA","晶宴 - 御豐廚務課","中式 - 合菜","新竹市","B"],
    [4547,"G6eL3xCGeyYseo3h5","晶宴 - 桃園客服課","中式 - 合菜","桃園市","B"],
    [4549,"LWkeDjGBZZHZZgyD4","晶宴 - 御豐客服課","中式 - 合菜","新竹市","B"],
    [4551,"ai2aoZyaif5jnCdnH","晶宴 - 桃園廚務課","中式 - 合菜","桃園市","B"],
    [4552,"hnNGqjhzbjgJuXLfL","台北國賓 - 天母中餐廳 2","中式 - 合菜","台北市","B"],
    [4573,"kiy5RuR7mFvBML7Hw","饗泰多 - 新月廣場店 (免稅) 追加","中式 - 合菜","宜蘭縣","B"],
    [4577,"TEMmoBZ73SvxRMfYY","燒肉LIKE-松江南京店","燒烤類 - 日式燒肉","台北市","B"],
    [4581,"Cnn9bkeXExbj3swQY","木盆 - 古亭門市","素食/蔬食 - 西式","台北市","C"],
    [4584,"Y7zptookrbWcTSuKp","KKH 南西承德店(內場)","中式 - 合菜","台北市","B"],
    [4587,"dotTkFJ3HscmuqYWG","KKH 南西承德店(外場)","中式 - 合菜","台北市","B"],
    [4598,"3KxojNk9EZFWriFDc","Origen團圓國際 - 試菜","西式 - 高價","台北市","B"],
    [4599,"3zBHX2BsNT8xxJxB9","Origen團圓國際 - 西廚外場","西式 - 高價","台北市","B"],
    [4600,"8kpf6NghAQiiK2dkE","Origen團圓國際 - 專案倉","西式 - 高價","台北市","B"],
    [4602,"Td5kt6f4gWTvpTJAv","Origen團圓國際 - 執行辦公室","西式 - 高價","台北市","B"],
    [4604,"bGhSXrLDtz6L2YmnJ","Origen團圓國際 - 西廚","西式 - 高價","台北市","B"],
    [4607,"ccEniNHhw8bJSz8FN","肉多多(台北西門店)","鍋類 - 台式","台北市","B"],
    [4608,"Fxp5uPNKnTMRRwrgF","本家長壽村","亞洲 - 韓式","台北市","B"],
    [4609,"NFisXm2hwPg2cnt8h","秋錦居酒屋","中式 - 熱炒","台北市","A"],
    [4624,"XHvnXzXT3ZmBup9Hk","Mia Cucina - 信義店(A11)(唯椿)","素食/蔬食 - 西式","台北市","C"],
    [4680,"DqaFb4awqtaqFG6tX","Mia Cucina - 南西店","素食/蔬食 - 西式","台北市","C"],
    [4691,"Yx7d8EBZqcD2ECS57","Miopane - 信義A8 (信義好膳)(麵包部)","素食/蔬食 - 西式","台北市","C"],
    [4776,"SZauzDDfkXfbpRzeN","慕舍酒店 - 專案倉","西式 - 高價","台北市","B"],
    [4778,"piHwfqm3wCaqTmL8T","慕舍酒店 - 酒吧","西式 - 高價","台北市","B"],
    [4779,"vLAYMsoh6Q4TApLSb","慕舍酒店 - 西廚","西式 - 高價","台北市","B"],
    [4822,"D4v4qayb2cEj6i9Y9","飽福商行 - 阿福號","健康餐盒","台北市","C"],
    [4825,"dtBpW52burfNpMzEq","樂芙健康餐盒","健康餐盒","台北市","C"],
    [4826,"8e9ekz6RTAj24rNRd","蔬醒vegeburger","早餐 - 早午餐","台北市","C"],
    [4827,"DqKPZjpaXdiHkYEqh","PokéPoké波奇波奇 - 新竹竹北店","健康餐盒","新竹縣","C"],
    [4828,"N2hmMyCKTmRxcgBgE","麥味登 - 新莊昌明店","早餐 - 傳統早餐店","新北市","C"],
    [4829,"WouFnu7y2axZzaPxD","麥町土司工房 - 天母士東店","早餐 - 早午餐","台北市","C"],
    [4833,"7kHzT9qG3mDkyoTE3","文湖21雞湯麵","中式 - 麵食","台北市","C"],
    [4838,"575L5jn3c5m2RHamz","麵線陳專業麵線 - 板橋貴興店","小吃 - 滷味","新北市","C"],
    [4839,"BkiSyZKNwgrpF2uT5","便當研究所","中式 - 飯食","新北市","C"],
    [4840,"GMLKjwPkcyzRtLybe","初飯包","健康餐盒","台北市","C"],
    [4842,"J2fr3bmXgsv4Bvfw2","六星便當松山民權店","中式 - 飯食","台北市","C"],
    [4843,"QJWRY7NbphKW3Guz6","飯飯先生","早餐 - 早午餐","台北市","C"],
    [4844,"SavJfWqemiAQTPceZ","世界素食館","素食/蔬食 - 中式","台北市","C"],
    [4852,"94xyAdLdgcRnR5hi8","麵屋蓮","日式 - 日式麵食專賣","台北市","C"],
    [4854,"PvX93X9GrSufTs6eE","NEST巢TEPPANYAKI","燒烤類 - 鐵板燒","台北市","B"],
    [4855,"TJNftgiCeDqhCYKKx","GiraPizza","西式 - 平價義式","台北市","B"],
    [4856,"Zb38jhKmsYZw39SSM","Library134","早餐 - 早午餐","台北市","C"],
    [4857,"fTxifEu8CBmzuSguF","Ooh Cha Cha - 板橋店 - 試菜單","素食/蔬食 - 西式","新北市","C"],
    [4858,"fZYg8TkLxECgaZm46","侯黑鍋物專賣店 - 四平店","鍋類 - 台式","台北市","B"],
    [4859,"hFPrjvGTNhFc8DJX3","Zackey朝起","早餐 - 早午餐","台北市","C"],
    [4860,"wjqmMo7ZE3376R6jZ","食肆天 - 馬偕小巷店","早餐 - 早午餐","台北市","C"],
    [4861,"arQuGLJmc4rzpvvjx","Caffè Le MANI 琢手咖啡","咖啡及輕食","台北市","C"],
    [4862,"bd4mNKxB7AMnC7rgN","盛櫥 - 追加單","早餐 - 早午餐","台北市","C"],
    [4864,"8RtbQtJrNWHukW6ka","Gonna-仁愛店","健康餐盒","台北市","C"],
    [4865,"8fvz7uQ2WajEibeuS","Gonna-內湖店","健康餐盒","台北市","C"],
    [4868,"GqqZ4hzAydSGxRCQ5","酌屋","日式 - 居酒屋","台北市","A"],
    [4872,"Wn9ZA98vuQqPJPj6L","築咯夢","小吃 - 夜市","新北市","C"],
    [4874,"YLwWQyKZbnQWYbvCR","Gonna-SOGO忠孝店","健康餐盒","台北市","C"],
    [4875,"dorNcPPqCRvMQXZSL","一定好食有限公司","健康餐盒","台北市","C"],
    [4877,"mZzQbc9sTxtc7AwwZ","Gonna-南港店","健康餐盒","台北市","C"],
    [4878,"p6NXc2xFCzFGrN9Tz","贏到足","鍋類 - 中價","台北市","B"],
    [4880,"E8mLL9NYd4kQtdcDD","呦呦韓式吐司","早餐 - 早午餐","台北市","C"],
    [4881,"RMnyvo8F8pf3qu2vb","元心燃 - 取消","鍋類 - 中價","台北市","B"],
    [4882,"nxRu2BDjEa7hXbHtQ","宣牛溫體牛肉火鍋","鍋類 - 中價","台北市","B"],
    [4883,"C4A9NZbvY36mA9zbT","春日Ramen","日式 - 日式麵食專賣","台北市","C"],
    [4885,"iPsh9DuxGEBFMzqNb","派特漢堡 - 松山店","素食/蔬食 - 西式","台北市","C"],
    [4886,"pu6oZBtZuumBniWuo","禪風茶樓","素食/蔬食 - 中式","台北市","C"],
    [4890,"PFFKwa2tLL3Z5riJ8","拾壹烏龍麵","日式 - 日式麵食專賣","台北市","C"],
    [4892,"tWnhmhWGyDXfkDrAi","牧牧沙拉(X","蔬食餐廳 - 複合式","台北市","C"],
    [4893,"A6zWMTgXTm8Dt9NF7","喜悅舒活藝文堂","素食/蔬食 - 中式","台北市","C"],
    [4896,"uKFDhrHZktaR97AEi","出一張嘴 - 南京店","燒烤類 - 其他","台北市","B"],
    [4902,"sKjfvN8mqtYnXygt7","義大利米蘭手工窯烤披薩","西式 - 高價","台北市","B"],
    [4903,"haBpFofY3MghGw7Qs","Jazzfun Chaffé","咖啡及輕食","台北市","C"],
    [4904,"Tu4RfKnphHjTaQZZ4","津宅喜料","中式 - 麵食","台北市","C"],
    [4908,"XgG2dXQLm2W7tTzmo","燒肉擔當 - 試菜","燒烤類 - 日式燒肉","台北市","B"],
    [4909,"q6qoEmZQe5DvHSbRr","B612餐酒館","西式 - 一般","台北市","A"],
    [4910,"xwoHh9xv89aiAmysz","燒肉中山信義店","燒烤類 - 其他","台北市","B"],
    [4911,"zo6RMs8boPWTXJQd4","好酥胡鹽酥雞","小吃 - 鹹酥雞","台北市","C"]
  ]
};

function renderAsahiPool(){
  const body=document.getElementById('asahi-pool-table');
  if(!body)return;
  const rows=ASAHI_POOL_SNAPSHOT.rows
    .map(([sourceRow,id,name,type,city,tier])=>({sourceRow,id,name,type,city,tier}))
    .sort((a,b)=>'ABC'.indexOf(a.tier)-'ABC'.indexOf(b.tier)||a.sourceRow-b.sourceRow);
  const counts=rows.reduce((result,row)=>{result[row.tier]=(result[row.tier]||0)+1;return result;},{});
  document.getElementById('pool-count-a').textContent=counts.A||0;
  document.getElementById('pool-count-b').textContent=counts.B||0;
  document.getElementById('pool-count-c').textContent=counts.C||0;
  document.getElementById('pool-count-held').textContent=ASAHI_POOL_SNAPSHOT.totalRows-rows.length;
  document.getElementById('pool-count-eligible').textContent=rows.length;

  const search=document.getElementById('asahi-pool-search');
  const tierFilter=document.getElementById('asahi-pool-tier');
  const stageFilter=document.getElementById('asahi-pool-stage');
  const empty=document.getElementById('asahi-pool-empty');
  const resultCount=document.getElementById('asahi-pool-result-count');
  const sourceBase='https://docs.google.com/spreadsheets/d/1Ubzqq_EKfJ8TDvo7KEBRG4KV4anXROxScoZAhPfS2gA/edit?gid=808112332';
  const tierLabels={A:'A｜直接啤酒情境',B:'B｜餐飲搭餐優先',C:'C｜先確認場景'};
  const qualificationFields=['目前酒類狀態','目前啤酒品牌','Asahi是否覆蓋','酒類販售資格','冷藏空間'];
  const STAGES=['待查證','查證中','通過','試點候選','淘汰'];
  const stageOf=q=>{
    const k=key=>known(q[key])?String(q[key]).trim():'';
    const pilot=k('Pilot意願');
    if(k('酒類販售資格')==='否'||k('冷藏空間')==='否'||k('Asahi是否覆蓋')==='是'||k('目前酒類狀態')==='已有 Asahi'||['暫無意願','拒絕'].includes(pilot))return '淘汰';
    const pass=k('酒類販售資格')==='是'&&k('冷藏空間')==='是'&&k('Asahi是否覆蓋')==='否'&&k('DecisionMaker')!==''&&k('DecisionMaker')!=='尚未建立關係';
    if(pass)return ['已確認願意 Pilot','有興趣'].includes(pilot)?'試點候選':'通過';
    return ['目前酒類狀態','目前啤酒品牌','Asahi是否覆蓋','酒類販售資格','冷藏空間','DecisionMaker','Pilot意願'].some(k)?'查證中':'待查證';
  };
  const getQualification=row=>window.asahiPoolQualification?.get({id:row.id,name:row.name})?.data||{};
  const known=value=>value!==undefined&&value!==null&&String(value).trim()!==''&&String(value).trim()!=='Unknown';
  const renderRows=()=>{
    const query=search.value.trim().toLowerCase();
    const visible=rows.filter(row=>(!tierFilter.value||row.tier===tierFilter.value)&&(!stageFilter.value||stageOf(getQualification(row))===stageFilter.value)&&`${row.name} ${row.type} ${row.city}`.toLowerCase().includes(query));
    body.replaceChildren();
    visible.forEach(row=>{
      const tr=document.createElement('tr');
      const stageCell=document.createElement('td'),stageBadge=document.createElement('span'),stage=stageOf(getQualification(row));
      stageBadge.className=`pool-stage-badge stage-${STAGES.indexOf(stage)}`;stageBadge.textContent=stage;stageCell.appendChild(stageBadge);
      const tier=document.createElement('td'),badge=document.createElement('span');
      badge.className=`pool-tier-badge tier-${row.tier.toLowerCase()}`;
      badge.textContent=tierLabels[row.tier];
      tier.appendChild(badge);
      const name=document.createElement('td'),strong=document.createElement('strong'),id=document.createElement('small');
      strong.textContent=row.name;id.textContent=`ID ${row.id}`;name.append(strong,id);
      const type=document.createElement('td');type.textContent=row.type||'店型未填（名稱線索分類，請複核）';
      const city=document.createElement('td');city.textContent=row.city||'未提供';
      const next=document.createElement('td'),qualification=getQualification(row);
      const status=document.createElement('span');
      status.className='pool-qualification-summary';
      status.textContent=`酒類：${known(qualification['目前酒類狀態'])?qualification['目前酒類狀態']:'Unknown'} · 啤酒：${known(qualification['目前啤酒品牌'])?qualification['目前啤酒品牌']:'Unknown'} · Asahi：${known(qualification['Asahi是否覆蓋'])?qualification['Asahi是否覆蓋']:'Unknown'}`;
      const edit=document.createElement('button');
      edit.type='button';edit.className='link-button pool-qualification-edit';edit.textContent='編輯 Qualification';
      edit.addEventListener('click',()=>window.asahiPoolQualification?.open(row));
      next.append(status,edit);
      const source=document.createElement('td'),link=document.createElement('a');
      link.href=`${sourceBase}&range=A${row.sourceRow}`;
      link.target='_blank';link.rel='noopener noreferrer';link.textContent=`第 ${row.sourceRow} 列`;
      source.appendChild(link);
      tr.append(stageCell,tier,name,type,city,next,source);body.appendChild(tr);
    });
    empty.hidden=visible.length>0;
    const board=document.getElementById('pool-pipeline-board');
    if(board){
      const scope=rows.filter(row=>row.tier==='A');
      const stageCounts=Object.fromEntries(STAGES.map(name=>[name,0]));
      scope.forEach(row=>{stageCounts[stageOf(getQualification(row))]+=1;});
      board.replaceChildren();
      STAGES.forEach((name,index)=>{
        const card=document.createElement('button');
        card.type='button';card.className=`pool-pipeline-stage stage-${index}${stageFilter.value===name?' active':''}`;
        const label=document.createElement('span'),count=document.createElement('strong');
        label.textContent=name;count.textContent=stageCounts[name];
        card.append(label,count);
        card.addEventListener('click',()=>{tierFilter.value='A';stageFilter.value=stageFilter.value===name?'':name;renderRows();});
        board.appendChild(card);
      });
      const total=document.getElementById('pool-pipeline-total');
      if(total)total.textContent=`A 級共 ${scope.length} 家`;
    }
    const qualified=rows.filter(row=>qualificationFields.every(key=>known(getQualification(row)[key]))).length;
    resultCount.textContent=`顯示 ${visible.length} / ${rows.length} 家候選 · 已補齊酒類狀態 ${qualified} 家 · 快照 ${ASAHI_POOL_SNAPSHOT.capturedAt}`;
  };
  search.addEventListener('input',renderRows);
  tierFilter.addEventListener('change',renderRows);
  stageFilter.addEventListener('change',renderRows);
  window.addEventListener('asahi-pool-qualification-updated',renderRows);
  document.getElementById('export-asahi-pool').addEventListener('click',()=>{
    const headers=['推進階段','初篩類別','客戶名稱','來源店型','城市','來源店號','試算表列','目前酒類狀態','目前啤酒品牌','Asahi是否覆蓋','酒類販售資格','冷藏空間','DecisionMaker','關係強度','Pilot意願','Qualification備註','下一步確認'];
    const csvRows=rows.map(row=>{
      const qualification=getQualification(row);
      return [stageOf(qualification),tierLabels[row.tier],row.name,row.type,row.city,row.id,row.sourceRow,...qualificationFields.map(key=>qualification[key]||'Unknown'),qualification.DecisionMaker||'Unknown',qualification['關係強度']||'Unknown',qualification['Pilot意願']||'Unknown',qualification['備註']||'','酒類資格、啤酒品牌、決策者、冷藏條件'];
    });
    const content=[headers,...csvRows].map(row=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(',')).join('\r\n');
    const blob=new Blob(['\uFEFF',content],{type:'text/csv;charset=utf-8'});
    const url=URL.createObjectURL(blob),anchor=document.createElement('a');
    anchor.href=url;anchor.download='asahi-customer-pool-first-pass.csv';anchor.click();
    URL.revokeObjectURL(url);
  });
  renderRows();
}

document.addEventListener('DOMContentLoaded',renderAsahiPool);
